from __future__ import annotations

TRADE_TERMS: list[tuple[str, str, str]] = [
    ("EXW", "EXW", "en"),
    ("EXW", "Ex Works", "en"),
    ("EXW", "工厂交货", "zh"),
    ("FCA", "FCA", "en"),
    ("FCA", "Free Carrier", "en"),
    ("FCA", "货交承运人", "zh"),
    ("FAS", "FAS", "en"),
    ("FAS", "Free Alongside Ship", "en"),
    ("FAS", "船边交货", "zh"),
    ("FOB", "FOB", "en"),
    ("FOB", "Free on Board", "en"),
    ("FOB", "free on board", "en"),
    ("FOB", "离岸价", "zh"),
    ("FOB", "船上交货", "zh"),
    ("FOB", "装运港船上交货", "zh"),
    ("CFR", "CFR", "en"),
    ("CFR", "C&F", "en"),
    ("CFR", "CNF", "en"),
    ("CFR", "Cost and Freight", "en"),
    ("CFR", "成本加运费", "zh"),
    ("CIF", "CIF", "en"),
    ("CIF", "Cost Insurance and Freight", "en"),
    ("CIF", "成本加保险费加运费", "zh"),
    ("CIF", "到岸价", "zh"),
    ("CPT", "CPT", "en"),
    ("CPT", "Carriage Paid To", "en"),
    ("CPT", "运费付至", "zh"),
    ("CIP", "CIP", "en"),
    ("CIP", "Carriage and Insurance Paid To", "en"),
    ("CIP", "运费保险费付至", "zh"),
    ("DAP", "DAP", "en"),
    ("DAP", "Delivered at Place", "en"),
    ("DAP", "目的地交货", "zh"),
    ("DPU", "DPU", "en"),
    ("DPU", "Delivered at Place Unloaded", "en"),
    ("DPU", "卸货地交货", "zh"),
    ("DDP", "DDP", "en"),
    ("DDP", "Delivered Duty Paid", "en"),
    ("DDP", "完税后交货", "zh"),
]
